name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "Dummy login done"

    - name: Build and push Docker image
      run: |
        docker build -t my-docker-app:${{ github.sha }} .
    - name: Log build details
      run: |
        echo "Commit SHA: ${{ github.sha }}"
        echo "Repository: ${{ github.repository }}"
